### ISSUE TITLE
Error out if pushing to the git remote fails

### ISSUE THREAD

**Issue by Cogitri** [maxice8/mkmr#20]
Right now we just go on an create an empty MR.

**Comment by maxice8** [comment]
What do you mean git remote fails ? if it fails to do what ? if you're creating a merge request then git remote part of mkmr worked as far as i can tell.

**Comment by Cogitri** [comment]
If `git push origin` fails mkmr will happily go on and create an empty MR

**Comment by maxice8** [comment]
We don't push to origin, the only action we do is git pull --rebase so mkmr is sure of which commits are part of the Merge Request and which ones are already in the repo.

mkmr can create empty MRs and will create them happily, then you can just do a git push origin -u origin HEAD yourself and the merge request will be automatically filled up with the correct commits.

**Comment by Cogitri** [comment]
So the user is always expected to push themselves? That seems a bit redundant

**Comment by maxice8** [comment]
at the moment, yes. we have no way of telling if the user already pushed and pushing a second time is more than a bit redundant

**Comment by maxice8** [comment]
If you find a way to reliably tell that the branch is already pushed in origin without incurring extra time on network feel free to fix it

**Comment by Cogitri** [comment]
Checking if the remote HEAD is the same as the local HEAD should do, I think. I'll look into it.

**Comment by Cogitri** [comment]
Hm, I think I changed my mind on this, since getting this right probably is pretty hard since the fork's branches might be behind us in which case we'd need to force push and messing that up would be very not nice
