### ISSUE TITLE
Use inquirer to prompt user for his token

### ISSUE THREAD

**Issue by maxice8** [maxice8/mkmr#6]
This switch should depend on the `--token` switch and will create all configuration (maybe even possibly ask the user to write the private_token key with inquirer?) and then exit.

@Cogitri

**Comment by maxice8** [comment]
I think it is better to just error out on the user and ask the user to generate a token and pass it via --token, which will be automatically written in the configuration

**Comment by Cogitri** [comment]
I guess either works - I'd just run the setup (without having a switch for it), when there's no config setup yet. I think the setup could ask for the Gitlab URL and the token.

**Comment by maxice8** [comment]
Sounds like a good compromise, use `inquirer` to prompt the user for the gitlab token and then write it out.

**Comment by maxice8** [comment]
done with #8
